# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hacker News API Doc
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/hacker-news-api-doc" # the subpath of your site, e.g. /blog
url: "https://allen-garvey.github.io" # the base hostname & protocol for your site
repo_url: "https://github.com/allen-garvey/hacker-news-api-doc"
future: true

# Build settings
markdown: kramdown
permalink: hacker-news-api-doc/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
